### ISSUE TITLE
PyPI release?

### ISSUE THREAD

**Issue by jamadden** [zopefoundation/z3c.recipe.sphinxdoc#10]
Could we get a PyPI release please? 

> Package Index Owner: pcardune, projekt01, srichter

Which I think are @strichter @pcardune and @projekt01 here on github.

Or if you'd prefer to give `jamadden` and `mgedmin` PyPI access (me and @mgedmin ) I'd be happy to take care of it.

Thank you!

**Comment by pcardune** [comment]
done. Which is to say, I've given you access to pypi :)

**Comment by jamadden** [comment]
Thank you!

I've pushed 1.1.0 to PyPI.
